### ISSUE TITLE
Feature Request:  trainers should be able to create new cards

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#17]
Our makerspace student techs should have the ability to create and associate new cards with users.  Could you please allow Makerportal users at the level of "trainer" to create new cards?

**Comment by bu-tegan** [comment]
Feature Added in commit 70c340a1b28c0d33ab4b412efb1e36031868f65f, currently unmerged as it requires testing. Do trainers need to be able to Edit cards for Users? Seems like it may be additional privileges that could be abused but if they make a mistake then and admin would have to fix the problem.

**Comment by bu-tegan** [comment]
Testing looks good, change merged. Will leave open until decision on trainers editing card assignments.

**Comment by bu-tegan** [comment]
Closing as no feedback received.
