### ISSUE TITLE
Bug fix:  enable refreshing of Makerportal site

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#19]
For me at least, hitting refresh on the Makerportal site does not work.  Some pages return a 404 error, while other pages take me  back to the previous version of the Makerportal site.  On that topic - I always have to do a hard refresh, bypassing my cache (shift F5) in order to get the page to load properly.  Is there something I should be doing on my end to stop this behavior?  Clearing my cache?

**Comment by bu-tegan** [comment]
These are due to server settings and not directly related to the code base. We do need to determine the proper redirect rules for the server software and add to the documentation. See documentation/Example Server Configurations

**Comment by bu-tegan** [comment]
Proper server configs for nginx provided in 98ded0b3871df9e8e5ff5cf9a9ee34ccf2ef2a27
