### ISSUE TITLE
Bug Fix:  the log has a lot of invalid entries

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#21]
Beginning at the time of 2019-10-14 07:45:04 there are several dozen lines of erroneous entries.

**Comment by bu-tegan** [comment]
This is due to data data hanging out in the old database (1.x was poorly conceived). The migration brought those invalid entries forward  and they can be removed if desired but this is not an issue related to the website project.
