### ISSUE TITLE
Creating new users makes *two* users

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#24]
When creating a new user I always use the Bucknell email address format of xxx###@bucknell.edu where x is a letter and # is a number.  However, the Makerportal system seems to automatically be taking that email address, querying the database of Bucknell users, and finding the **friendly** email address as well.  Then the Makerportal system creates **two** users in the database, one for the email address I enter and one for the friendly email address.  This causes problems because I add certifications to the account associated with the first email address but the card will often be associated with the second account.

Could you please fix the system so that a second user account is not always created for the friendly email address?

**Comment by bu-tegan** [comment]
This is an issue with using the API and the web interface with different standards for data and not an issue with the management portal per say. Opening bug against Bucknell's internal script using the API.
