### ISSUE TITLE
Feature Request:  add ability for users to check account balances

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#29]
This is most likely a non-trivial request as I assume it would require changing user types or privileges.

For folks who are in the Coffee Club, it would be nice for them to have the ability to check their account balances.  At the moment I have to manually go in and determine this and let folks know.  With the update to the software running on the Pi's I will gain the ability to track account balances which will make that piece easier for me.  However, I would still need to check this myself for each user request.

**Comment by bu-tegan** [comment]
commit 6cc26976b2ff6fe10f0c1a92c7520907e1a411b1
